Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray** 



In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
arr1 = np.array([1,2,3,4,5])
print(arr1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
np.random.seed(44)
x = np.random.rand(3,4)
print(x)

  


# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
y = np.zeros((3,4), int)
print(y)


# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
z = np.ones((3,4), int)
print(z)


[[0.83484215 0.1047961  0.74464048 0.36050084]
 [0.35931084 0.60923838 0.39377955 0.40907261]
 [0.50990241 0.71014799 0.96052623 0.45662111]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
print(np.arange(4,25,4))
print(np.linspace(3,4, num=25))

[ 4  8 12 16 20 24]
[3.         3.04166667 3.08333333 3.125      3.16666667 3.20833333
 3.25       3.29166667 3.33333333 3.375      3.41666667 3.45833333
 3.5        3.54166667 3.58333333 3.625      3.66666667 3.70833333
 3.75       3.79166667 3.83333333 3.875      3.91666667 3.95833333
 4.        ]


### Basic array operations
- algebraic operations 
- logical operations

In [5]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [6]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))



[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [7]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 
print(np.sum(a, axis=0))

# Write a NumPy function to get the sum of the array 'a' along axis=1 
print(np.sum(a, axis=1))




[ 6 17 14]
[10 13 14]


In [8]:
# Write a NumPy function to reverse the array 'a' 
print(np.flip(a))


# Write a NumPy function to reverse the array 'a' along axis=0
print(np.flip(a,0))


# Write a NumPy function to reverse the array 'a' along axis=1
print(np.flip(a,1))



[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [9]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [10]:
# Write a NumPy function to sort the array 'a' 
print(np.sort(a))

# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a,0))

# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a,1))

# Write a NumPy function to sort the array 'a' in descending order along axis=0
x= np.sort(a,0)
print(np.flip(x,0))


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [72]:
 # Write a NumPy function to argsort the array along axis=0
np.argsort(a, axis=0)

# Write a NumPy function to argsort the array along axis=1
np.argsort(a, axis=1)


array([[2, 0, 1],
       [0, 2, 1],
       [0, 2, 1]])

In [12]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a,b), axis=0)

# Note: You can do the same function using stacking, discover and try that :)


array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [13]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [14]:
# Write a NumPy function to get the Number of dimensions
np.ndim(a)

# Write a NumPy function to get the Shape of the array 
np.shape(a)

# Write a NumPy function to get the Size of the array
np.size(a)


9

In [15]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a.reshape(1,9)


array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [16]:
# Write a NumPy function to add a new axis to the array 'a'
arr1 = a[np.newaxis]
# arr1.shape
arr2 = np.expand_dims(a, axis=0)
# arr2.shape
# Note : Show atleast two different ways of doing this 


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [17]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [18]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
print(a[:2 , 1:])
print(a[2])
print(a[1,2])
print(a[(0,1),(2,1)])

# Show all three - indexing by a integer, indexing by a tuple, using range


[[6 0]
 [3 1]]
[1 8 5]
1
[0 3]


In [19]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
x = np.arange(11)
new_arr = x>4
print(x[new_arr])

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
new_arr1 = (x>4) & (x%2==0)
print(x[new_arr1])

#  or we can also use
filter_arr =[]
for y in x:
  if (y>4) and (y%2==0):
    filter_arr.append(True)
  else :
     filter_arr.append(False) 
print(x[filter_arr])

[ 5  6  7  8  9 10]
[ 6  8 10]
[ 6  8 10]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
x = a.copy()
print(np.add(x,1))


[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset 

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [40]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d, columns = ['sepal length', 'sepal length', 'petal length', 'petal width'])
df.dropna(axis=0)


sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [42]:
# Write a Pandas function to find the correlation between the first two columns.
df['sepal length'].corr(df['sepal width'])



-0.10936924995064937

In [43]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
column_3 = df['petal length']
mean = column_3.mean()
median = column_3.median()
deviation = column_3.std()
print(mean , median, deviation)


3.758666666666666 4.35 1.7644204199522626


In [47]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
from math import pi
def calculate_volume(row):
    sepal_length = row['sepal length']
    petal_length = row['petal length']
    volume = (pi * petal_length * (sepal_length ** 2)) / 3
    return volume


df['volume'] = df.apply(calculate_volume, axis=1)

print(df.head())

   sepal length  sepal width  petal length  petal width     volume
0           5.1          3.5           1.4          0.2  38.132652
1           4.9          3.0           1.4          0.2  35.200498
2           4.7          3.2           1.3          0.2  30.072372
3           4.6          3.1           1.5          0.2  33.238050
4           5.0          3.6           1.4          0.2  36.651914


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [49]:
x = np.arange(4, dtype=np.int64)
des_array = np.ones_like(x)
print(des_array)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [55]:
x=np.arange(1,10)
myArray = np.split(x, [4,6])
print(myArray)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [56]:
np.random.seed(42)  

x = np.random.randint(0, 10, size=(2, 5))

print("Array x:")
print(x)

max_values = np.amax(x, axis=1)
min_values = np.amin(x, axis=1)

max_indices = np.argmax(x, axis=1)
min_indices = np.argmin(x, axis=1)

print("\nMaximum values along the second axis:")
print(max_values)
print("Indices of maximum values along the second axis:")
print(max_indices)

print("\nMinimum values along the second axis:")
print(min_values)
print("Indices of minimum values along the second axis:")
print(min_indices)

Array x:
[[6 3 7 4 6]
 [9 2 6 7 4]]

Maximum values along the second axis:
[7 9]
Indices of maximum values along the second axis:
[2 0]

Minimum values along the second axis:
[3 2]
Indices of minimum values along the second axis:
[1 1]


### Pandas

Run the following load command and solve the following questions

In [57]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [61]:
df = pd.DataFrame(iris, columns=names)

species_count = df['species'].value_counts()

print(species_count)

b'Iris-setosa'        50
b'Iris-versicolor'    50
b'Iris-virginica'     50
Name: species, dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [68]:
df['petallength'] = pd.to_numeric(df['petallength'], errors='coerce')
bins = [0, 3, 5, np.inf]
labels = ['small', 'medium', 'large']
df['petal_length_category'] = pd.cut(df['petallength'], bins=bins, labels=labels, right = False)
print(df)

    sepallength sepalwidth  petallength petalwidth            species  \
0        b'5.1'     b'3.5'          1.4     b'0.2'     b'Iris-setosa'   
1        b'4.9'     b'3.0'          1.4     b'0.2'     b'Iris-setosa'   
2        b'4.7'     b'3.2'          1.3     b'0.2'     b'Iris-setosa'   
3        b'4.6'     b'3.1'          1.5     b'0.2'     b'Iris-setosa'   
4        b'5.0'     b'3.6'          1.4     b'0.2'     b'Iris-setosa'   
..          ...        ...          ...        ...                ...   
145      b'6.7'     b'3.0'          5.2     b'2.3'  b'Iris-virginica'   
146      b'6.3'     b'2.5'          5.0     b'1.9'  b'Iris-virginica'   
147      b'6.5'     b'3.0'          5.2     b'2.0'  b'Iris-virginica'   
148      b'6.2'     b'3.4'          5.4     b'2.3'  b'Iris-virginica'   
149      b'5.9'     b'3.0'          5.1     b'1.8'  b'Iris-virginica'   

    petal_length_category  
0                   small  
1                   small  
2                   small  
3          

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [71]:
M_F_petallength = df['petallength'].value_counts().idxmax()
print(M_F_petallength)

1.5
